name: flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Publish using the reusable workflow from dart-lang.
jobs:
  publish-package:
    runs-on: ubuntu-latest

    env:
      working-directory: ./phone_client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}} 

      - name: Run tests
        run: flutter test
        working-directory: ${{env.working-directory}} 

